[package]
name = "lilka"
version = "0.1.0"
entrypoint = "lib.typ"
repository = "https://github.com/syrkis/lilka"
authors = ["Noah Syrkis"]
license = "MIT"
description = "A presentation template."
compiler = "0.13.0"
categories = ["presentation"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
